# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'publish'
    workingDir: '/'
    publishRegistry: 'useFeed'
    publishFeed: '7f4df7ba-202a-4d68-810a-6f07636caa25/a46de90f-e622-44f5-8e13-300cd384ee2a'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
